services:
  - type: web
    name: chess-ai-backend
    env: python
    region: frankfurt
    plan: free
    rootDir: ./backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
